name: stream_chatter
description: Chat App implemented using Clean Architecture.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: 6.1.2
  stream_chat_flutter: 1.3.0-beta
  uuid: 2.2.2

  firebase_core: 0.7.0
  google_sign_in: 4.5.9
  firebase_auth: 0.20.0+1
  firebase_storage: 7.0.0
  shared_preferences: 0.5.12+4
  http: any

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
     - assets/